set backspace=indent,eol,start
set nobackup
set nowritebackup
set history=50
colorscheme Tomorrow
:syntax on
:set hlsearch
:set incsearch
:set smartindent
:set textwidth=70
:set wrapmargin=10
:set softtabstop=4
:set shiftwidth=4
:set tabstop=4
:set expandtab
:set wildmode=list:longest
:set wildmenu
:set noswapfile
:set nowb
:set showcmd
:set showmode
:set autoread
:set mouse=a
:set mousehide
